// Vendored word data for Etymology race (../etymology.ts).
//
// Source: the Etymon project (github.com/avan36/Etymology, live at
// avan36.github.io/Etymology). Every word, gloss, stage and story below is
// copied from its data/words/*.json files (seed, germanic, french, latin,
// greek, world, modern); language names come from data/languages/core.json and
// world.json. Etymon's etymologies follow the OED, Etymonline and Wiktionary.
//
// `origin` is the game's answer: the language English took the word from
// (Etymon's `origin` field), with Old/Middle English, the French varieties
// (Old, Middle, Anglo-Norman) and the Latin varieties folded together so the
// choices stay fair. Generated once; edit by hand against the source. The
// stories' em dashes are swapped for the site's commas, colons and brackets.

export type RaceStage = { lang: string; form: string; year: number; meaning?: string };
export type RaceWord = { word: string; gloss: string; origin: string; path: RaceStage[]; story: string };

/** Etymon's display names for every language the journeys below pass through. */
export const RACE_LANGS: Record<string, string> = {
  alg: "Algonquian languages",
  ang: "Old English",
  ar: "Arabic",
  aus: "Australian Aboriginal languages",
  bnt: "Bantu languages",
  cs: "Czech",
  cy: "Welsh",
  de: "German",
  dum: "Middle Dutch",
  en: "English",
  enm: "Middle English",
  es: "Spanish",
  fa: "Persian",
  fr: "French",
  frm: "Middle French",
  fro: "Old French",
  ga: "Irish",
  gd: "Scottish Gaelic",
  "gem-pro": "Proto-Germanic",
  "gmw-pro": "Proto-West Germanic",
  goh: "Old High German",
  grc: "Ancient Greek",
  haw: "Hawaiian",
  hbo: "Biblical Hebrew",
  hi: "Hindi",
  ht: "Haitian Creole",
  "ine-pro": "Proto-Indo-European",
  it: "Italian",
  ja: "Japanese",
  la: "Latin",
  "la-lat": "Late Latin",
  "la-med": "Medieval Latin",
  ml: "Malayalam",
  ms: "Malay",
  nan: "Min Nan (Hokkien)",
  nci: "Classical Nahuatl",
  nl: "Dutch",
  non: "Old Norse",
  pro: "Old Occitan",
  pt: "Portuguese",
  sa: "Sanskrit",
  sga: "Old Irish",
  sw: "Swahili",
  ta: "Tamil",
  tnq: "Taíno",
  ty: "Tahitian",
  xno: "Anglo-Norman",
  yi: "Yiddish",
};

export const RACE_WORDS: RaceWord[] = [
  {
    word: "water",
    gloss: "the clear liquid that falls as rain and fills rivers and seas",
    origin: "Old English",
    path: [{ lang: "ine-pro", form: "*wódr̥", year: -4000 }, { lang: "gem-pro", form: "*watōr", year: -500 }, { lang: "ang", form: "wæter", year: 700 }, { lang: "enm", form: "water", year: 1200 }, { lang: "en", form: "water", year: 1500 }],
    story: "One of the oldest words you use. Six thousand years ago on the steppe, *wódr̥ already meant water; its descendants include Russian vodka (\"little water\") and Greek hydor, which gave us hydrogen.",
  },
  {
    word: "wolf",
    gloss: "a wild animal of the dog family that hunts in packs",
    origin: "Old English",
    path: [{ lang: "ine-pro", form: "*wĺ̥kʷos", year: -4000 }, { lang: "gem-pro", form: "*wulfaz", year: -500 }, { lang: "ang", form: "wulf", year: 700 }, { lang: "enm", form: "wolf", year: 1200 }, { lang: "en", form: "wolf", year: 1500 }],
    story: "Greek lúkos and Latin lupus are the same word, which is why a Greek werewolf is a lycanthrope. Wolves prowl through Germanic names too: Rudolf is 'fame-wolf', Wolfgang 'wolf-path', and Beowulf may be 'bee-wolf', a riddling name for a bear.",
  },
  {
    word: "weird",
    gloss: "strange, unusual, uncanny",
    origin: "Old English",
    path: [{ lang: "ine-pro", form: "*wert-", year: -4000, meaning: "to turn" }, { lang: "gem-pro", form: "*wurþiz", year: -500, meaning: "fate" }, { lang: "ang", form: "wyrd", year: 800, meaning: "fate, destiny" }, { lang: "enm", form: "werd, wird", year: 1300, meaning: "fate" }, { lang: "en", form: "weird", year: 1606, meaning: "having power over fate (Macbeth's weird sisters)" }, { lang: "en", form: "weird", year: 1815, meaning: "odd, strange" }],
    story: "Wyrd was fate, literally 'what turns out'. Shakespeare's weird sisters in Macbeth were the sisters of fate, and from them, by the early 1800s, weird drifted to 'uncanny' and then to merely 'odd'.",
  },
  {
    word: "gossip",
    gloss: "casual talk about other people's private lives",
    origin: "Old English",
    path: [{ lang: "ang", form: "godsibb", year: 1000, meaning: "godparent ('related in God')" }, { lang: "enm", form: "godsib, gossib", year: 1300, meaning: "close friend" }, { lang: "en", form: "gossip", year: 1560, meaning: "an idle talker" }, { lang: "en", form: "gossip", year: 1811, meaning: "idle talk" }],
    story: "A gossip was a godparent, godsibb, 'related in God' (sib as in sibling). Godparents were close friends, especially the women who came to keep a new mother company at a birth, and their chatter turned the word into idle talk.",
  },
  {
    word: "silly",
    gloss: "foolish, lacking good sense",
    origin: "Old English",
    path: [{ lang: "gem-pro", form: "*sēligaz", year: -500, meaning: "blessed, happy" }, { lang: "ang", form: "sǣliġ", year: 900, meaning: "happy, blessed, lucky" }, { lang: "enm", form: "seli, sely", year: 1300, meaning: "innocent; pitiable" }, { lang: "en", form: "silly", year: 1570, meaning: "feeble; foolish" }],
    story: "Few words have fallen so far: Old English sǣliġ meant happy and blessed, as German selig still does. It slid to innocent, then to pitiable, then to feeble-minded, and by Shakespeare's day silly meant foolish.",
  },
  {
    word: "Wednesday",
    gloss: "the day of the week after Tuesday",
    origin: "Old English",
    path: [{ lang: "gem-pro", form: "*Wōdanaz", year: -500, meaning: "the frenzied one" }, { lang: "ang", form: "Wōdnesdæġ", year: 900, meaning: "Woden's day" }, { lang: "enm", form: "Wednesday", year: 1200 }, { lang: "en", form: "Wednesday", year: 1500 }],
    story: "Woden's day: the Old English name of Odin, chief of the gods, matched with Mercury (Latin diēs Mercuriī, French mercredi). His name is related to Old English wōd, 'frenzied, inspired', and the spelling still keeps a d we stopped saying centuries ago.",
  },
  {
    word: "sky",
    gloss: "the space above the earth where clouds and stars are seen",
    origin: "Old Norse",
    path: [{ lang: "ine-pro", form: "*(s)kewH-", year: -4000, meaning: "to cover" }, { lang: "gem-pro", form: "*skiwją", year: -500, meaning: "cloud" }, { lang: "non", form: "ský", year: 900, meaning: "cloud" }, { lang: "enm", form: "skie", year: 1220, meaning: "cloud" }, { lang: "en", form: "sky", year: 1500 }],
    story: "A Viking gift. In Old Norse ský meant \"cloud\", and so it did in early English. By 1300 it had pushed aside the native word heofon (which survives as heaven) for the vault above us.",
  },
  {
    word: "egg",
    gloss: "the oval object laid by a bird, containing a developing chick",
    origin: "Old Norse",
    path: [{ lang: "ine-pro", form: "*h₂ōwyóm", year: -4000 }, { lang: "gem-pro", form: "*ajją", year: -500 }, { lang: "non", form: "egg", year: 900 }, { lang: "enm", form: "egge", year: 1340 }, { lang: "en", form: "egg", year: 1500 }],
    story: "English already had its own word, ǣġ (plural ǣġru, later eyren), and for two centuries the two fought it out. In 1490 the printer William Caxton told of a London merchant who asked a Kentish woman for 'eggys' and was told she spoke no French: she only knew 'eyren'. Latin ōvum (oval) is a distant cousin.",
  },
  {
    word: "window",
    gloss: "an opening in a wall, usually filled with glass, to let in light and air",
    origin: "Old Norse",
    path: [{ lang: "non", form: "vindauga", year: 900, meaning: "wind-eye" }, { lang: "enm", form: "windoge", year: 1225 }, { lang: "enm", form: "windowe", year: 1300 }, { lang: "en", form: "window", year: 1500 }],
    story: "A 'wind-eye': Old Norse vindauga, from vindr (wind) + auga (eye), a hole in the roof that let smoke out and air in. It replaced the native ēagþyrel, 'eye-hole', and then saw off French fenestre, which hung on in English until the 1500s.",
  },
  {
    word: "they",
    gloss: "the people or things already mentioned (with them, their)",
    origin: "Old Norse",
    path: [{ lang: "gem-pro", form: "*þai", year: -500 }, { lang: "non", form: "þeir, þeim, þeira", year: 900, meaning: "they, them, their" }, { lang: "enm", form: "thei", year: 1200 }, { lang: "en", form: "they, them, their", year: 1500 }],
    story: "Even pronouns came from the Vikings, which is very rare between languages. Old English hīe (they), heom (them) and hiera (their) were easily confused with he, him and her; Norse þeir, þeim and þeira took over, they first in the north and them and their by about 1500. The 'em of 'let 'em go' is the last echo of heom.",
  },
  {
    word: "berserk",
    gloss: "out of control with anger or excitement",
    origin: "Old Norse",
    path: [{ lang: "non", form: "berserkr", year: 1100, meaning: "a frenzied warrior" }, { lang: "en", form: "berserker", year: 1822, meaning: "a frenzied Norse warrior" }, { lang: "en", form: "berserk", year: 1940, meaning: "wildly out of control" }],
    story: "A berserkr was a Norse warrior who fought in a trance-like fury. The name probably means 'bear-shirt', though some read it as 'bare-shirt', fighting without armour. Walter Scott brought it into English in 1822, and people have been going berserk since the 20th century.",
  },
  {
    word: "ransack",
    gloss: "to search a place roughly, making a mess and stealing things",
    origin: "Old Norse",
    path: [{ lang: "non", form: "rannsaka", year: 900, meaning: "to search a house (for stolen goods)" }, { lang: "enm", form: "ransaken", year: 1200, meaning: "to search" }, { lang: "en", form: "ransack", year: 1500, meaning: "to plunder" }],
    story: "Old Norse rannsaka, from rann, 'house', + saka, 'to seek', was a lawful search of a house for stolen goods. By about 1300 the searchers had become the robbers, and ransack meant to plunder.",
  },
  {
    word: "beef",
    gloss: "the meat of a cow",
    origin: "French",
    path: [{ lang: "ine-pro", form: "*gʷṓws", year: -4000, meaning: "cow" }, { lang: "la", form: "bos, bovis", year: -200, meaning: "ox, cow" }, { lang: "fro", form: "buef", year: 1100, meaning: "ox" }, { lang: "xno", form: "boef", year: 1250 }, { lang: "enm", form: "beef", year: 1300 }, { lang: "en", form: "beef", year: 1500 }],
    story: "After 1066, the Saxons who tended the animals kept their English words (cow, swine, sheep), while the Norman lords who ate them used French: beef, pork, mutton. The class divide is still on your menu.",
  },
  {
    word: "mortgage",
    gloss: "a loan to buy property, with the property as security",
    origin: "French",
    path: [{ lang: "ine-pro", form: "*mer-", year: -4000, meaning: "to die" }, { lang: "la", form: "mortuus", year: -50, meaning: "dead" }, { lang: "fro", form: "mort gage", year: 1200, meaning: "a dead pledge" }, { lang: "fro", form: "morgage", year: 1250 }, { lang: "enm", form: "morgage", year: 1390 }, { lang: "en", form: "mortgage", year: 1500 }],
    story: "A mortgage is a “death pledge”. The classic explanation, from the 17th-century jurist Sir Edward Coke, is that the deal dies either way: when the debt is paid off, or when the borrower fails to pay and the land is lost to them forever.",
  },
  {
    word: "curfew",
    gloss: "a rule requiring people to stay indoors after a certain time",
    origin: "French",
    path: [{ lang: "la", form: "cooperīre + focus", year: -50, meaning: "to cover + hearth" }, { lang: "fro", form: "covrefeu", year: 1200, meaning: "cover fire!" }, { lang: "xno", form: "coeverfu", year: 1250 }, { lang: "enm", form: "curfeu", year: 1285, meaning: "the evening signal to cover fires" }, { lang: "en", form: "curfew", year: 1800, meaning: "an order to stay indoors" }],
    story: "Curfew means “cover the fire”. In medieval towns a bell rang each evening as the signal to bank down or cover hearth fires for the night, a sensible precaution in crowded timber streets. The popular tale that William the Conqueror imposed it to crush the Saxons is doubtful.",
  },
  {
    word: "jeopardy",
    gloss: "danger of loss, harm or failure",
    origin: "French",
    path: [{ lang: "la", form: "iocus + partītus", year: -50, meaning: "game + divided" }, { lang: "fro", form: "jeu parti", year: 1250, meaning: "a divided game; an even chance" }, { lang: "enm", form: "iuparti", year: 1300, meaning: "a chess problem; an uncertain chance" }, { lang: "en", form: "jeopardy", year: 1500, meaning: "danger, risk" }],
    story: "Jeopardy was a game with evenly divided chances: Old French jeu parti. Early English used it for a chess problem, and from “an even chance” it was a short step to danger. Latin iocus, “jest”, also gave joke and juggler.",
  },
  {
    word: "dandelion",
    gloss: "a wild plant with yellow flowers and jagged leaves",
    origin: "French",
    path: [{ lang: "ine-pro", form: "*h₃dónts", year: -4000, meaning: "tooth" }, { lang: "la-med", form: "dēns leōnis", year: 1200, meaning: "lion's tooth" }, { lang: "frm", form: "dent de lion", year: 1400, meaning: "lion's tooth" }, { lang: "enm", form: "dent-de-lyon", year: 1430 }, { lang: "en", form: "dandelion", year: 1513 }],
    story: "The jagged leaves looked like a lion’s teeth: dent de lion. Modern French has moved on and calls it pissenlit, “wet-the-bed”, after its fame as a diuretic.",
  },
  {
    word: "restaurant",
    gloss: "a place where people pay to sit and eat meals",
    origin: "French",
    path: [{ lang: "ine-pro", form: "*steh₂-", year: -4000, meaning: "to stand" }, { lang: "la", form: "restaurāre", year: -50, meaning: "to restore, to repair" }, { lang: "fr", form: "restaurant", year: 1765, meaning: "a restorative broth" }, { lang: "fr", form: "restaurant", year: 1780, meaning: "an eating house" }, { lang: "en", form: "restaurant", year: 1821 }],
    story: "A restaurant was first a soup. In 1760s Paris, restaurants were restorative meat broths, sold to delicate customers in shops that took the name of their dish. The word simply means “restoring”.",
  },
  {
    word: "alibi",
    gloss: "proof that one was elsewhere when a crime happened; an excuse",
    origin: "Latin",
    path: [{ lang: "ine-pro", form: "*h₂el-", year: -4000, meaning: "beyond, other" }, { lang: "la", form: "alibī", year: -50, meaning: "elsewhere" }, { lang: "en", form: "alibi", year: 1727, meaning: "the plea of having been elsewhere" }, { lang: "en", form: "alibi", year: 1912, meaning: "an excuse" }],
    story: "In Latin it is only an adverb, “elsewhere”. Eighteenth-century courts used it for the defence that the accused was somewhere else at the time. By 1912 Americans were using it for any excuse at all.",
  },
  {
    word: "virus",
    gloss: "a tiny infectious agent that multiplies inside living cells; a harmful computer program",
    origin: "Latin",
    path: [{ lang: "la", form: "vīrus", year: -50, meaning: "poison, venom; slime" }, { lang: "enm", form: "virus", year: 1400, meaning: "a venomous substance" }, { lang: "en", form: "virus", year: 1898, meaning: "an infectious agent smaller than bacteria" }, { lang: "en", form: "virus", year: 1972, meaning: "a self-copying computer program" }],
    story: "To Romans vīrus was venom, slime or a rank smell. Doctors used it loosely for any cause of disease until Martinus Beijerinck showed in 1898 that tobacco mosaic disease came from something small enough to pass through filters that trap bacteria. The computer sense first appeared in a 1972 science-fiction novel.",
  },
  {
    word: "street",
    gloss: "a public road in a town or village, usually with buildings along it",
    origin: "Latin",
    path: [{ lang: "ine-pro", form: "*sterh₃-", year: -4000, meaning: "to spread" }, { lang: "la", form: "strāta (via)", year: -100, meaning: "a paved road" }, { lang: "gmw-pro", form: "*strātu", year: 300 }, { lang: "ang", form: "strǣt", year: 700 }, { lang: "enm", form: "strete", year: 1200 }, { lang: "en", form: "street", year: 1500 }],
    story: "Roman roads were viae strātae, “paved ways”. Germanic tribes borrowed strāta before they ever reached Britain (hence German Straße and Dutch straat), and the Anglo-Saxons gave the name to the old Roman roads they found, like Watling Street.",
  },
  {
    word: "cheese",
    gloss: "a food made from pressed milk curds",
    origin: "Latin",
    path: [{ lang: "la", form: "cāseus", year: -100 }, { lang: "gmw-pro", form: "*kāsī", year: 300 }, { lang: "ang", form: "ċīese", year: 800 }, { lang: "enm", form: "chese", year: 1200 }, { lang: "en", form: "cheese", year: 1500 }],
    story: "Germanic farmers borrowed Latin cāseus in Roman times, which is why cheese, German Käse and Dutch kaas match. French and Italian took another road: fromage and formaggio come from Latin formāticus, cheese “shaped in a mould”.",
  },
  {
    word: "kitchen",
    gloss: "a room where food is prepared and cooked",
    origin: "Latin",
    path: [{ lang: "ine-pro", form: "*pekʷ-", year: -4000, meaning: "to cook, to ripen" }, { lang: "la-lat", form: "coquīna", year: 300 }, { lang: "gmw-pro", form: "*kukīnā", year: 400 }, { lang: "ang", form: "cyċene", year: 900 }, { lang: "enm", form: "kichene", year: 1200 }, { lang: "en", form: "kitchen", year: 1500 }],
    story: "The same Latin word reached English twice: once through early Germanic contact, becoming the Anglo-Saxon cyċene, and again some 900 years later as French cuisine. Cook and biscuit (“twice cooked”) simmer from the same root.",
  },
  {
    word: "ignoramus",
    gloss: "an ignorant or stupid person",
    origin: "Latin",
    path: [{ lang: "ine-pro", form: "*ǵneh₃-", year: -4000, meaning: "to know" }, { lang: "la", form: "ignōrāmus", year: -50, meaning: "we do not know" }, { lang: "en", form: "ignoramus", year: 1577, meaning: "a grand jury's endorsement rejecting an indictment" }, { lang: "en", form: "ignoramus", year: 1616, meaning: "an ignorant person" }],
    story: "A grand jury that found the evidence too thin wrote Ignōrāmus, “we do not know”, on the back of the bill of indictment. George Ruggle’s 1615 comedy Ignoramus, which mocked a bumbling lawyer of that name, turned the legal formula into an insult.",
  },
  {
    word: "decimate",
    gloss: "to kill or destroy a large part of",
    origin: "Latin",
    path: [{ lang: "ine-pro", form: "*déḱm̥", year: -4000, meaning: "ten" }, { lang: "la", form: "decimāre", year: -50, meaning: "to execute every tenth man (from decem, ten)" }, { lang: "en", form: "decimate", year: 1600, meaning: "to kill one in every ten" }, { lang: "en", form: "decimate", year: 1660, meaning: "to destroy a large part of" }],
    story: "A Roman army punishment: a mutinous unit was divided into groups of ten, and each group killed one of its own, chosen by lot. Since the 1660s decimate has meant destroying a large part of something, a shift that pedants still grumble about.",
  },
  {
    word: "cosmos",
    gloss: "the universe seen as an ordered whole",
    origin: "Greek",
    path: [{ lang: "grc", form: "κόσμος (kosmos)", year: -500, meaning: "order; ornament; the ordered universe" }, { lang: "en", form: "cosmos", year: 1650 }],
    story: "Kosmos meant order and also ornament: anything well arranged. Pythagoras is said to have been the first to call the universe a kosmos, an orderly whole. The 'ornament' sense survives in cosmetic, the art of putting your face in order.",
  },
  {
    word: "protagonist",
    gloss: "the leading character in a story, play or real event",
    origin: "Greek",
    path: [{ lang: "ine-pro", form: "*h₂eǵ-", year: -4000, meaning: "to drive, to lead" }, { lang: "grc", form: "ἀγών (agōn)", year: -700, meaning: "contest, struggle" }, { lang: "grc", form: "πρωταγωνιστής (prōtagōnistēs)", year: -350, meaning: "actor who plays the first part" }, { lang: "en", form: "protagonist", year: 1671 }],
    story: "Classical Greek tragedy used at most three speaking actors: the prōtagōnistēs (first contender), the deuteragonist (second) and the tritagonist (third). The pro- is not 'for' but prōtos, first, so strictly a play has only one protagonist.",
  },
  {
    word: "yacht",
    gloss: "a sailing or motor boat used for pleasure or racing",
    origin: "Dutch",
    path: [{ lang: "nl", form: "jachtschip, jaght", year: 1550, meaning: "hunting ship" }, { lang: "en", form: "yacht", year: 1557 }],
    story: "Short for Dutch jachtschip, 'hunting ship', a fast boat for chasing down pirates and smugglers. Charles II brought the pleasure-boat craze home from his Dutch exile in 1660, when the Dutch presented him with the yacht Mary.",
  },
  {
    word: "boss",
    gloss: "a person in charge of workers or an organisation",
    origin: "Dutch",
    path: [{ lang: "nl", form: "baas", year: 1600, meaning: "master" }, { lang: "en", form: "boss", year: 1649 }],
    story: "American English picked up baas, 'master', from the Dutch of New Amsterdam, later New York. It was a handy word in a new democracy where free workers disliked calling anyone 'master'.",
  },
  {
    word: "cookie",
    gloss: "a small sweet baked biscuit; a small file a website stores in your browser",
    origin: "Dutch",
    path: [{ lang: "nl", form: "koekje", year: 1650, meaning: "little cake" }, { lang: "en", form: "cookie", year: 1703 }, { lang: "en", form: "cookie", year: 1994, meaning: "browser data file" }],
    story: "Dutch koekje, 'little cake', came into English through the Dutch of New York. Britain still mostly says biscuit, but since 1994 every web user has met cookies: Netscape's Lou Montulli named them after programmers' 'magic cookies'.",
  },
  {
    word: "Santa Claus",
    gloss: "a legendary figure who brings presents at Christmas",
    origin: "Dutch",
    path: [{ lang: "dum", form: "Sinter Niklaas", year: 1400, meaning: "Saint Nicholas" }, { lang: "nl", form: "Sinterklaas, Sante Klaas", year: 1700 }, { lang: "en", form: "Santa Claus", year: 1773 }],
    story: "From Dutch Sinterklaas, 'Saint Nicholas', whose feast the Dutch of New York kept. A New York newspaper of 1773 mentioned 'St. A Claus'; the 1823 poem 'A Visit from St. Nicholas' and Thomas Nast's cartoons turned him into the jolly man in red.",
  },
  {
    word: "kindergarten",
    gloss: "a school or class for young children",
    origin: "German",
    path: [{ lang: "de", form: "Kindergarten", year: 1840, meaning: "children's garden" }, { lang: "en", form: "kindergarten", year: 1852 }],
    story: "The educator Friedrich Fröbel coined it in 1840 for a school where children would be tended like plants in a garden. German immigrants carried the idea to America, and English kept the German word, garden and all.",
  },
  {
    word: "angst",
    gloss: "a feeling of deep anxiety or dread",
    origin: "German",
    path: [{ lang: "ine-pro", form: "*h₂emǵʰ-", year: -4000, meaning: "narrow, tight" }, { lang: "goh", form: "angust", year: 900 }, { lang: "de", form: "Angst", year: 1500, meaning: "fear" }, { lang: "en", form: "angst", year: 1849 }],
    story: "German Angst, 'fear', taken into English in the 1840s and given philosophical weight by translations of Kierkegaard and Freud. It shares a root with anger, anguish and anxiety: the feeling of a tightening in the chest.",
  },
  {
    word: "hamster",
    gloss: "a small rodent with cheek pouches, often kept as a pet",
    origin: "German",
    path: [{ lang: "goh", form: "hamustro", year: 900 }, { lang: "de", form: "Hamster", year: 1500 }, { lang: "en", form: "hamster", year: 1607 }],
    story: "From German Hamster, from Old High German hamustro, perhaps a loan from a Slavic language. German has even made a verb of it: hamstern, to hoard, after the animal's habit of stuffing its cheeks.",
  },
  {
    word: "poltergeist",
    gloss: "a ghost blamed for loud noises and moving objects",
    origin: "German",
    path: [{ lang: "de", form: "Poltergeist", year: 1600, meaning: "rumbling ghost" }, { lang: "en", form: "poltergeist", year: 1848 }],
    story: "A 'rumbling ghost': German poltern, 'to make a racket, to rattle', + Geist, 'spirit'. Geist and English ghost are siblings.",
  },
  {
    word: "pretzel",
    gloss: "a crisp, salted biscuit or bread baked in a knot",
    origin: "German",
    path: [{ lang: "la", form: "bracchium", year: -100, meaning: "arm" }, { lang: "la-med", form: "brachitella", year: 800 }, { lang: "goh", form: "brezitella", year: 1000 }, { lang: "de", form: "Brezel, Bretzel", year: 1500 }, { lang: "en", form: "pretzel", year: 1824 }],
    story: "German Brezel goes back to Latin bracchium, 'arm', because the knot looks like a pair of folded arms. A much-repeated legend credits a monk who shaped dough like arms crossed in prayer.",
  },
  {
    word: "glitch",
    gloss: "a sudden, usually temporary, malfunction",
    origin: "Yiddish",
    path: [{ lang: "yi", form: "גליטש (glitsh)", year: 1900, meaning: "a slip" }, { lang: "en", form: "glitch", year: 1962 }],
    story: "Probably from Yiddish glitsh, 'a slip', from glitshn, 'to slide'. It was radio engineers' slang until 1962, when astronaut John Glenn explained it in print as 'a spike or change in voltage'; computers did the rest.",
  },
  {
    word: "chutzpah",
    gloss: "extreme self-confidence or audacity",
    origin: "Yiddish",
    path: [{ lang: "hbo", form: "חֻצְפָּה (ḥuṣpā)", year: 200, meaning: "insolence" }, { lang: "yi", form: "חוצפה (khutspe)", year: 1600, meaning: "nerve, cheek" }, { lang: "en", form: "chutzpah", year: 1883 }],
    story: "Hebrew ḥuṣpā meant insolence; in Yiddish khutspe can mean outrageous nerve or grudging admiration for it. The classic illustration: the man who murders his parents and then pleads for mercy because he is an orphan.",
  },
  {
    word: "umbrella",
    gloss: "a folding canopy on a stick, used against rain or sun",
    origin: "Italian",
    path: [{ lang: "la", form: "umbra", year: -50, meaning: "shade, shadow" }, { lang: "la", form: "umbella", year: 50, meaning: "sunshade, parasol" }, { lang: "it", form: "ombrella", year: 1500 }, { lang: "en", form: "umbrello", year: 1609 }, { lang: "en", form: "umbrella", year: 1650 }],
    story: "A 'little shade', from Latin umbra, and at first a sunshade. When Jonas Hanway carried one against the rain through 1750s London, people jeered, since umbrellas were thought fit only for women; within a generation every gentleman had one.",
  },
  {
    word: "influenza",
    gloss: "a contagious viral infection of the airways; flu",
    origin: "Italian",
    path: [{ lang: "la-med", form: "influentia", year: 1300, meaning: "a flowing in (of power from the stars)" }, { lang: "it", form: "influenza", year: 1500, meaning: "influence; an epidemic" }, { lang: "en", form: "influenza", year: 1743 }, { lang: "en", form: "flu", year: 1839 }],
    story: "Italian influenza meant 'influence', specifically the influence of the stars, which were blamed for outbreaks of disease. English borrowed it during a European epidemic in 1743, and by 1839 had shortened it to flu.",
  },
  {
    word: "quarantine",
    gloss: "a period of isolation to stop a disease spreading",
    origin: "Italian",
    path: [{ lang: "la", form: "quadrāgintā", year: -50, meaning: "forty" }, { lang: "it", form: "quaranta giorni", year: 1400, meaning: "forty days" }, { lang: "en", form: "quarantine", year: 1663 }],
    story: "From the 1370s, Ragusa (Dubrovnik) and later Venice made ships arriving from plague-stricken ports wait offshore, first for thirty days, later for forty: quaranta giorni. Why forty is unclear; the biblical forty days of Lent and of the Flood may have suggested it.",
  },
  {
    word: "volcano",
    gloss: "a mountain with a vent through which lava and gas erupt",
    origin: "Italian",
    path: [{ lang: "la", form: "Vulcānus", year: -200, meaning: "Vulcan, god of fire" }, { lang: "it", form: "vulcano", year: 1500, meaning: "a fire-mountain (first, the island of Vulcano)" }, { lang: "en", form: "volcano", year: 1613 }],
    story: "Named after Vulcan, the Roman god of fire and the forge, whose workshop was imagined beneath Vulcano, a smoking island north of Sicily. Italian turned the island's name into the word for any fire-mountain.",
  },
  {
    word: "mosquito",
    gloss: "a small flying insect whose female sucks blood",
    origin: "Spanish",
    path: [{ lang: "la", form: "musca", year: -50, meaning: "fly" }, { lang: "es", form: "mosca", year: 1200, meaning: "fly" }, { lang: "es", form: "mosquito", year: 1500, meaning: "little fly" }, { lang: "en", form: "mosquito", year: 1583 }],
    story: "Simply a 'little fly' in Spanish, from mosca. Spanish explorers used it for the biting insects of the Americas. Three centuries later scientists showed that mosquitoes carry malaria and yellow fever, making this little fly the deadliest animal on Earth.",
  },
  {
    word: "alligator",
    gloss: "a large reptile of the Americas and China, related to crocodiles",
    origin: "Spanish",
    path: [{ lang: "la", form: "lacertus", year: -50, meaning: "lizard" }, { lang: "es", form: "el lagarto", year: 1500, meaning: "the lizard" }, { lang: "en", form: "lagarto", year: 1568 }, { lang: "en", form: "alligator", year: 1600 }],
    story: "Spanish sailors in the Caribbean called the creature el lagarto, 'the lizard'. English swallowed the article along with the noun, and el lagarto became alligator. Lizard comes from the same Latin lacertus.",
  },
  {
    word: "hurricane",
    gloss: "a violent tropical storm with very strong winds",
    origin: "Spanish",
    path: [{ lang: "tnq", form: "hurakán", year: 1500 }, { lang: "es", form: "huracán", year: 1520 }, { lang: "en", form: "furacano", year: 1555 }, { lang: "en", form: "hurricane", year: 1650 }],
    story: "From Taíno, via Spanish. Early English writers couldn't settle on a spelling, trying furacano, haurachana, herycano and uracan, and Shakespeare's King Lear rages: 'You cataracts and hurricanoes, spout!' The modern form settled in the mid-1600s.",
  },
  {
    word: "chocolate",
    gloss: "a food made from roasted, ground cacao seeds, usually sweetened",
    origin: "Spanish",
    path: [{ lang: "nci", form: "chocolātl", year: 1550, meaning: "a cacao drink" }, { lang: "es", form: "chocolate", year: 1580 }, { lang: "en", form: "chocolate", year: 1604 }],
    story: "The Aztecs drank cacao frothy, bitter and often spiced with chili; Spanish colonists sweetened it. The exact Nahuatl source is a puzzle, since chocolātl doesn't appear in the earliest records and may be a blend, but its ending is probably ātl, water.",
  },
  {
    word: "flamingo",
    gloss: "a tall pink wading bird with a long neck",
    origin: "Portuguese",
    path: [{ lang: "la", form: "flamma", year: -50, meaning: "flame" }, { lang: "pro", form: "flamenc", year: 1300, meaning: "flame-coloured" }, { lang: "pt", form: "flamengo", year: 1500 }, { lang: "en", form: "flamingo", year: 1565 }],
    story: "The flame-coloured bird: Provençal flamenc, from flama, 'flame', plus a Germanic ending meaning 'like'. Flamingos get their pink from pigments in the algae and tiny shrimp they eat.",
  },
  {
    word: "cobra",
    gloss: "a venomous snake that spreads a hood when threatened",
    origin: "Portuguese",
    path: [{ lang: "la", form: "colubra", year: -50, meaning: "snake" }, { lang: "pt", form: "cobra de capello", year: 1500, meaning: "snake with a hood" }, { lang: "en", form: "cobra de capello", year: 1671 }, { lang: "en", form: "cobra", year: 1802 }],
    story: "Portuguese explorers in India named it cobra de capello, 'snake with a hood', for the flap it spreads when threatened. English kept only the 'snake': cobra is just Portuguese for serpent, from Latin colubra.",
  },
  {
    word: "mango",
    gloss: "a sweet, juicy tropical fruit with a large stone",
    origin: "Portuguese",
    path: [{ lang: "ta", form: "மாங்காய் (māṅkāy)", year: 200, meaning: "mango fruit" }, { lang: "ml", form: "മാങ്ങ (māṅṅa)", year: 1400 }, { lang: "pt", form: "manga", year: 1510 }, { lang: "en", form: "mango", year: 1582 }],
    story: "Portuguese traders reaching Kerala, on India's south-west coast, picked up Malayalam māṅṅa, a sister of Tamil māṅkāy, 'mango fruit', and carried manga around their empire. English took it from them in the 1580s.",
  },
  {
    word: "shampoo",
    gloss: "liquid soap for washing hair",
    origin: "Hindi",
    path: [{ lang: "sa", form: "चपयति (capayati)", year: -200, meaning: "kneads, presses" }, { lang: "hi", form: "चाँपो (cā̃po)", year: 1700, meaning: "press! knead!" }, { lang: "en", form: "shampoo", year: 1762, meaning: "to massage" }, { lang: "en", form: "shampoo", year: 1860, meaning: "hair soap" }],
    story: "At first it meant a full-body massage, brought home from India in the 1760s. Sake Dean Mahomed opened \"shampooing\" baths in Brighton in 1814; only in the 1860s did the word move up to the scalp.",
  },
  {
    word: "pajamas",
    gloss: "loose trousers and jacket for sleeping in (British: pyjamas)",
    origin: "Hindi",
    path: [{ lang: "ine-pro", form: "*pṓds", year: -4000, meaning: "foot" }, { lang: "fa", form: "پای‌جامه (pāy-jāma)", year: 1500, meaning: "leg garment" }, { lang: "hi", form: "पाजामा (pājāmā)", year: 1700, meaning: "loose drawstring trousers" }, { lang: "en", form: "pyjamas", year: 1800 }],
    story: "Persian pāy (leg) + jāma (garment): loose drawstring trousers worn across Mughal India. British colonists took them up as comfortable sleepwear in the 1800s. Persian pāy goes back to the same ancient root as English foot.",
  },
  {
    word: "jungle",
    gloss: "a dense tropical forest",
    origin: "Hindi",
    path: [{ lang: "sa", form: "जङ्गल (jaṅgala)", year: -500, meaning: "arid, sparsely wooded land" }, { lang: "hi", form: "जंगल (jaṅgal)", year: 1600, meaning: "wild, uncultivated land; forest" }, { lang: "en", form: "jungle", year: 1776 }],
    story: "Sanskrit jaṅgala meant dry, rough country. In Hindi jaṅgal became wild, uncultivated land of any kind, often overgrown, and the British turned it into the dense, steamy tropical forest of their imaginations. Kipling's Jungle Book (1894) fixed the image.",
  },
  {
    word: "avatar",
    gloss: "an incarnation of a deity; a figure representing a person online",
    origin: "Sanskrit",
    path: [{ lang: "sa", form: "अवतार (avatāra)", year: -200, meaning: "descent (of a god to earth)" }, { lang: "en", form: "avatar", year: 1784, meaning: "an incarnation of a Hindu god" }, { lang: "en", form: "avatar", year: 1985, meaning: "a user's figure in a virtual world" }],
    story: "Ava- (down) + tṛ (to cross): the descent of a god into the world, as when Vishnu becomes Krishna or Rama. In the mid-1980s the designers of Lucasfilm's online world Habitat borrowed it for the figure a player sends into virtual space, and James Cameron's 2009 film made it a household word.",
  },
  {
    word: "karma",
    gloss: "the idea that your actions shape your future; fate as payback",
    origin: "Sanskrit",
    path: [{ lang: "sa", form: "कर्मन् (karman)", year: -1000, meaning: "act, deed; its consequences" }, { lang: "en", form: "karma", year: 1827 }],
    story: "Karman simply means 'act' or 'deed', and in Hindu and Buddhist thought the consequences every deed carries into this life and the next. English took it up in the 1820s; by the late 20th century it was everyday slang for cosmic payback.",
  },
  {
    word: "karaoke",
    gloss: "singing along to recorded backing music",
    origin: "Japanese",
    path: [{ lang: "grc", form: "ὀρχήστρα (orkhēstra)", year: -400, meaning: "the dancing floor of a theatre" }, { lang: "en", form: "orchestra", year: 1606 }, { lang: "ja", form: "オーケストラ (ōkesutora)", year: 1900, meaning: "orchestra" }, { lang: "ja", form: "カラオケ (karaoke)", year: 1970, meaning: "empty orchestra" }, { lang: "en", form: "karaoke", year: 1979 }],
    story: "Kara (empty) + oke, short for ōkesutora: an 'empty orchestra', the band without the singer. The word is a round trip. Orchestra was the Greek dancing floor in front of the stage; it reached Japan through English and came back as karaoke in the late 1970s.",
  },
  {
    word: "emoji",
    gloss: "a small digital picture used to express an idea or emotion",
    origin: "Japanese",
    path: [{ lang: "ja", form: "絵 (e) + 文字 (moji)", year: 1990, meaning: "picture + written character" }, { lang: "ja", form: "絵文字 (emoji)", year: 1995 }, { lang: "en", form: "emoji", year: 1997 }],
    story: "E (picture) + moji (written character). Its likeness to emotion and emoticon is pure coincidence. Japanese mobile phones of the late 1990s made them famous, notably Shigetaka Kurita's set of 176 for NTT Docomo in 1999, and in 2015 Oxford Dictionaries named one, 😂 'Face with Tears of Joy', its Word of the Year.",
  },
  {
    word: "tsunami",
    gloss: "a huge sea wave caused by an earthquake or eruption",
    origin: "Japanese",
    path: [{ lang: "ja", form: "津波 (tsunami)", year: 1600, meaning: "harbour wave (tsu 'harbour' + nami 'wave')" }, { lang: "en", form: "tsunami", year: 1897 }],
    story: "Tsu (harbour) + nami (wave): fishermen out at sea might barely notice the swell, then come home to find their harbour wrecked. Lafcadio Hearn introduced the word to English in 1897. Scientists prefer it to 'tidal wave', since tides have nothing to do with it, and the Indian Ocean disaster of 2004 made it universal.",
  },
  {
    word: "ketchup",
    gloss: "a thick, sweet tomato sauce",
    origin: "Malay",
    path: [{ lang: "nan", form: "膎汁 (kê-tsiap)", year: 1600, meaning: "brine of pickled fish" }, { lang: "ms", form: "kicap", year: 1650, meaning: "fish or soy sauce" }, { lang: "en", form: "catchup", year: 1690 }, { lang: "en", form: "ketchup", year: 1711 }],
    story: "Probably from Hokkien kê-tsiap, a fermented fish sauce that British traders met in Southeast Asia (Malay has kicap). English cooks tried to imitate it with mushrooms, walnuts and oysters; tomato ketchup didn't appear until the early 1800s.",
  },
  {
    word: "curry",
    gloss: "a dish of meat or vegetables in a spiced sauce",
    origin: "Tamil",
    path: [{ lang: "ta", form: "கறி (kaṟi)", year: 1000, meaning: "a sauce or relish eaten with rice" }, { lang: "en", form: "curry", year: 1598 }],
    story: "Tamil kaṟi was a spiced sauce eaten with rice, probably passed on by Portuguese traders, who wrote it caril. Britain's first curry house, the Hindoostane Coffee House, opened in London in 1810. To 'curry favour' is a different word entirely, from Old French, about grooming a horse.",
  },
  {
    word: "ghoul",
    gloss: "an evil spirit that robs graves and feeds on corpses; a morbid person",
    origin: "Arabic",
    path: [{ lang: "ar", form: "غول (ghūl)", year: 600, meaning: "a desert demon that devours travellers and the dead" }, { lang: "en", form: "ghoul", year: 1786 }],
    story: "In Arabian folklore a ghūl haunts the desert, luring travellers to their deaths and feeding on corpses. English met it in 1786 in the translation of William Beckford's Gothic tale Vathek. The winking star Algol takes its name from Arabic ra's al-ghūl, 'the demon's head'.",
  },
  {
    word: "hummus",
    gloss: "a dip of mashed chickpeas, tahini, lemon and garlic",
    origin: "Arabic",
    path: [{ lang: "ar", form: "حمص (ḥummuṣ)", year: 1200, meaning: "chickpeas" }, { lang: "en", form: "hummus", year: 1955 }],
    story: "Arabic ḥummuṣ simply means 'chickpeas'; the dip's full name is ḥummuṣ bi-ṭaḥīna, chickpeas with tahini. English cookbooks noticed it in the 1950s, and by the 2000s it had become a supermarket staple far from the eastern Mediterranean.",
  },
  {
    word: "whisky",
    gloss: "a spirit distilled from malted grain",
    origin: "Scottish Gaelic",
    path: [{ lang: "ine-pro", form: "*wódr̥", year: -4000, meaning: "water" }, { lang: "sga", form: "uisce", year: 800, meaning: "water" }, { lang: "gd", form: "uisge beatha", year: 1500, meaning: "water of life" }, { lang: "en", form: "whisky", year: 1715 }],
    story: "Gaelic uisge beatha, 'water of life', a translation of the alchemists' Latin aqua vitae. English first borrowed the whole phrase as usquebaugh, then kept only the water. Uisge descends from the same ancient root as English water and Russian vodka.",
  },
  {
    word: "galore",
    gloss: "in abundance (always placed after its noun)",
    origin: "Irish",
    path: [{ lang: "ga", form: "go leor", year: 1600, meaning: "enough, sufficiently" }, { lang: "en", form: "galore", year: 1675 }],
    story: "From Irish go leor, 'enough, to sufficiency'. It is one of very few English words that follow the noun they describe, just as the Irish phrase does: whisky galore, bargains galore.",
  },
  {
    word: "smithereens",
    gloss: "small broken pieces",
    origin: "Irish",
    path: [{ lang: "ga", form: "smidirín", year: 1800, meaning: "a little fragment (from smiodar, fragment)" }, { lang: "en", form: "smithereens", year: 1829 }],
    story: "Irish smiodar is a fragment and smidirín a little one; English added its own plural -s. It is almost never heard outside one phrase: blown to smithereens.",
  },
  {
    word: "corgi",
    gloss: "a short-legged herding dog with a fox-like head",
    origin: "Welsh",
    path: [{ lang: "ine-pro", form: "*ḱwṓ", year: -4000, meaning: "dog" }, { lang: "cy", form: "cor + ci", year: 1500, meaning: "dwarf + dog" }, { lang: "en", form: "corgi", year: 1926 }],
    story: "Welsh cor (dwarf) + ci (dog): a dwarf dog, bred to herd cattle by nipping at their heels. Ci comes from the same ancient root as hound and cynic. Queen Elizabeth II owned more than thirty corgis over her reign.",
  },
  {
    word: "robot",
    gloss: "a machine that carries out complex actions automatically",
    origin: "Czech",
    path: [{ lang: "ine-pro", form: "*h₃erbʰ-", year: -4000, meaning: "to change status" }, { lang: "cs", form: "robota", year: 1500, meaning: "forced labour" }, { lang: "cs", form: "robot", year: 1920, meaning: "artificial worker (Čapek, R.U.R.)" }, { lang: "en", form: "robot", year: 1923 }],
    story: "Coined for Karel Čapek's 1920 play R.U.R. (his brother Josef suggested it), from Czech robota, the forced labour serfs owed their lords. Distant cousin of English orphan and German Arbeit.",
  },
  {
    word: "kangaroo",
    gloss: "a large marsupial that moves by hopping",
    origin: "Australian Aboriginal languages",
    path: [{ lang: "aus", form: "gangurru (Guugu Yimidhirr)", year: 1770, meaning: "a large grey kangaroo" }, { lang: "en", form: "kangaroo", year: 1770 }],
    story: "In 1770, while Captain Cook's Endeavour was being repaired on the Endeavour River in Queensland, the crew noted the local name for the animal. A popular myth says it meant 'I don't understand you', but in the 1970s the linguist John Haviland found that Guugu Yimidhirr speakers still call a large grey kangaroo gangurru.",
  },
  {
    word: "ukulele",
    gloss: "a small four-stringed guitar",
    origin: "Hawaiian",
    path: [{ lang: "haw", form: "ʻukulele", year: 1880, meaning: "jumping flea (ʻuku 'flea' + lele 'jumping')" }, { lang: "en", form: "ukulele", year: 1896 }],
    story: "Portuguese immigrants from Madeira brought a small guitar, the machete, to Hawaii in 1879; Hawaiians renamed it ʻukulele, 'jumping flea', perhaps for the player's darting fingers. King Kalākaua championed it, and it swept the American mainland after 1915.",
  },
  {
    word: "safari",
    gloss: "an expedition to watch or hunt wild animals, especially in Africa",
    origin: "Swahili",
    path: [{ lang: "ar", form: "سفر (safar)", year: 700, meaning: "journey" }, { lang: "sw", form: "safari", year: 1800, meaning: "journey, expedition" }, { lang: "en", form: "safari", year: 1890 }],
    story: "Swahili safari, 'journey', from Arabic safar, a legacy of centuries of Indian Ocean trade along the East African coast. Victorian hunters made it mean an expedition to shoot game; today most safaris shoot only photographs.",
  },
  {
    word: "zombie",
    gloss: "a corpse said to be revived by magic; a person who seems lifeless",
    origin: "Haitian Creole",
    path: [{ lang: "bnt", form: "nzambi (Kimbundu)", year: 1600, meaning: "god" }, { lang: "ht", form: "zonbi", year: 1750, meaning: "a corpse raised by sorcery" }, { lang: "en", form: "zombie", year: 1871 }],
    story: "From Haitian Creole zonbi, a corpse raised by sorcery to labour as a slave, probably from a Central African word such as Kimbundu nzambi, 'god'. Hollywood's White Zombie (1932) made it a movie monster; oddly, George Romero's Night of the Living Dead (1968) never uses the word, calling its walking dead 'ghouls'.",
  },
  {
    word: "tattoo",
    gloss: "a permanent design made on the skin with ink and needles",
    origin: "Tahitian",
    path: [{ lang: "ty", form: "tatau", year: 1700, meaning: "a marking on the skin" }, { lang: "en", form: "tattow", year: 1769 }, { lang: "en", form: "tattoo", year: 1800 }],
    story: "Captain Cook wrote in Tahiti in 1769 that 'both sexes paint their bodys, Tattow as it is called in their language'. Sailors took up the practice with gusto. The military tattoo, a drum signal, is an unrelated word from Dutch doe den tap toe, 'turn off the tap'.",
  },
  {
    word: "skunk",
    gloss: "a black-and-white American mammal that sprays a foul smell",
    origin: "Algonquian languages",
    path: [{ lang: "alg", form: "squnck", year: 1630 }, { lang: "en", form: "skunk", year: 1634 }],
    story: "From a southern New England Algonquian language. Linguists trace it to a Proto-Algonquian word built from roots meaning 'to urinate' and 'fox', a fair description of an animal that defends itself by spraying.",
  },
  {
    word: "serendipity",
    gloss: "the knack of making happy discoveries by accident",
    origin: "Made in English",
    path: [{ lang: "fa", form: "سرندیپ (Sarandīp)", year: 1000, meaning: "Sri Lanka" }, { lang: "en", form: "Serendip", year: 1754, meaning: "as in The Three Princes of Serendip" }, { lang: "en", form: "serendipity", year: 1754 }],
    story: "Horace Walpole coined it in a 1754 letter, after a Persian fairy tale, The Three Princes of Serendip (an old name for Sri Lanka), whose heroes were ‘always making discoveries, by accidents and sagacity, of things which they were not in quest of’. It stayed a rarity until 20th-century scientists adopted it.",
  },
  {
    word: "nerd",
    gloss: "a person devoted to an intellectual or technical pursuit; once, a dull, socially awkward person",
    origin: "Made in English",
    path: [{ lang: "en", form: "nerd", year: 1950, meaning: "a creature in Dr. Seuss's If I Ran the Zoo" }, { lang: "en", form: "nerd", year: 1951, meaning: "a square, a drip" }, { lang: "en", form: "nerd", year: 1980, meaning: "a tech enthusiast" }],
    story: "The first known nerd is a small, cross-looking creature in Dr. Seuss's If I Ran the Zoo (1950). A year later Newsweek reported that in Detroit someone who once would be called a drip or a square was now ‘a nerd’. Whether the slang grew from Seuss nobody knows, but by the 1980s the nerds were running Silicon Valley.",
  },
  {
    word: "quiz",
    gloss: "a test of knowledge, often as a game",
    origin: "Made in English",
    path: [{ lang: "en", form: "quiz", year: 1782, meaning: "an odd or eccentric person" }, { lang: "en", form: "quiz", year: 1796, meaning: "to mock, make fun of" }, { lang: "en", form: "quiz", year: 1867, meaning: "a test" }],
    story: "Legend says a Dublin theatre manager, Richard Daly, bet in 1791 that he could make a nonsense word famous in two days, and had urchins chalk QUIZ on walls all over the city. A lovely tale, but quiz is recorded years before 1791, and the story surfaces only decades later. It first meant an odd person, then a mockery, and in 1860s America a test.",
  },
  {
    word: "OK",
    gloss: "all right; acceptable",
    origin: "Made in English",
    path: [{ lang: "en", form: "oll korrect", year: 1839, meaning: "a joke spelling of ‘all correct’" }, { lang: "en", form: "o.k.", year: 1839 }, { lang: "en", form: "OK", year: 1840 }],
    story: "Boston newspapers of the 1830s had a craze for jokey abbreviations of misspellings: O.W. for ‘oll wright’, K.Y. for ‘know yuse’. On 23 March 1839 the Boston Morning Post printed ‘o.k.’ for ‘all correct’, and in 1840 supporters of President Martin Van Buren, ‘Old Kinderhook’, formed O.K. Clubs. The other jokes died; OK conquered the planet.",
  },
  {
    word: "gerrymander",
    gloss: "to redraw electoral boundaries to favour one party",
    origin: "Made in English",
    path: [{ lang: "en", form: "Gerry + salamander", year: 1812 }, { lang: "en", form: "gerrymander", year: 1812 }],
    story: "In 1812 Massachusetts Governor Elbridge Gerry signed a bill redrawing state senate districts to help his party. One district north of Boston was so contorted that a cartoon in the Boston Gazette gave it claws and wings: the ‘Gerry-mander’, half Gerry, half salamander. (Gerry said his name with a hard G.)",
  },
];
